### ISSUE TITLE
AT Application Feedback

### ISSUE THREAD

**Issue by md-5** [md-5/SpecialSource#28]
@AbrarSyed please elaborate what you need here

**Comment by AbrarSyed** [comment]
So we have a few options regarding feedback..
1) we add something to the AccessMap that records which ATs were used and which were not, so that I can pull out that information in ForgeGradle and notify the user that their AT may be malformed.
2) you throw some type of exception when you find that an AT rule is inapplicable

I dont't know much about how SS works except its public APi that I use, and thus I dont know which is best and easiest to implement. However from my side in ForgeGradle, I can work around either one.

This is the function in FG where I plan on using the feature.
https://github.com/MinecraftForge/ForgeGradle/blob/master/src/main/java/net/minecraftforge/gradle/tasks/ProcessJarTask.java#L165

Wowo, actually.. looking at that now.. There might be ways for me to get what I want by hacking arround SS and the AccessMap.. still want it in the upstream if possible though...

**Comment by md-5** [comment]
Yeah I can do option 1.

**Comment by md-5** [comment]
The above should be sufficient, let me know when its done and I can make a release.
